[project]
name = "koi-net-CHANGE-NAME-node"
version = "0.1.0"
description = "<YOUR NODE DESCRIPTION>"
authors = [
    # {name = "<YOUR NAME>", email = "<YOUR EMAIL>"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "koi-net~=2.0"
]

# [project.urls]
# Homepage = "<YOUR NODE REPO URL>"